services:
  fastapi:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  nextjs:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    networks:
      - app-network
    depends_on:
      - fastapi
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge
